apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: {{ .Values.managedDisk.name }}
    diskURI: {{ .Values.managedDisk.uri }}
