kind: Secret
apiVersion: v1
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  root-password: {{ .Values.rootPassword | b64enc }}
  wordpress-password: {{ .Values.wordpressPassword | b64enc }}
