apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: {{ .Values.mysql.managedDisk.name }}
    diskURI: {{ .Values.mysql.managedDisk.uri }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  volumeMode: Filesystem
  volumeName: mysql-pv
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  azureDisk:
    kind: Managed
    diskName: {{ .Values.wordpress.managedDisk.name }}
    diskURI: {{ .Values.wordpress.managedDisk.uri }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
  volumeMode: Filesystem
  volumeName: wordpress-pv
  storageClassName: ""