kind: Secret
apiVersion: v1
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc }}
  mysql-wordpress-password: {{ .Values.mysql.wordpressPassword | b64enc }}