apiVersion: v1
kind: PersistentVolume
metadata:
  name: mailu-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.storageShare.nfsInternalDNSOrIP }}
    path: {{ .Values.storageShare.nfsMountPath }}
