apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailu-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 32Gi
  selector: 
    matchLabels:
      type: nfs
