apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mysql.fullname" . }}
spec:
  storageClassName: {{ include "mysql.fullname" . }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: {{ .Values.persistentVolume.diskId }}
    fsType: {{ .Values.persistentVolume.fsType }}
