apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
type: Opaque
data:
  rootPassword: {{ .Values.mysql.rootPassword | b64enc }}
  wordpressUsername: {{ .Values.mysql.wordpressUsername | b64enc }}
  wordpressPassword: {{ .Values.mysql.wordpressPassword | b64enc }}
