apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mysql.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mysql.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mysql.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - bash
              - "-c"
              - |
                mysqladmin -h localhost -uroot -p${MYSQL_ROOT_PASSWORD} ping
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
              - bash
              - "-c"
              - |
                mysql -h localhost -uroot -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1"
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: rootPassword
                  name: {{ include "mysql.fullname" . }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.wordpressDB }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: wordpressUsername
                  name: {{ include "mysql.fullname" . }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: wordpressPassword
                  name: {{ include "mysql.fullname" . }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
              subPath: mysql
      volumes:
        # - name: data
        #   hostPath:
        #     path: /tmp/mysql
        #     type: DirectoryOrCreate
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mysql.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
# ---
{{- /*
apiVersion: v1
kind: Pod
metadata:
  name: pods-simple-pod
spec:
  serviceAccountName: {{ include "mysql.serviceAccountName" . }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 4 }}
  containers:
    - image: busybox
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      name: pods-simple-container
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
  volumes:
    # - name: data
    #   hostPath:
    #     path: /tmp/mysql
    #     type: DirectoryOrCreate
    - name: data
      persistentVolumeClaim:
        claimName: {{ include "mysql.fullname" . }}
*/}}
