apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wordpress.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /wp-login.php
              port: http
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /wp-login.php
              port: http
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.wordpress.mysqlHost }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.wordpress.mysqlDB }}
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.fullname" . }}
                  key: mysqlUsername
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.fullname" . }}
                  key: mysqlPassword
            - name: WORDPRESS_TABLE_PREFIX
              value: wp_
          volumeMounts:
            - name: data
              mountPath: /var/www/html
              subPath: wordpress
      volumes:
        # - name: data
        #   hostPath:
        #     path: /tmp/wordpress
        #     type: DirectoryOrCreate
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "wordpress.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
# ---
{{- /*
apiVersion: v1
kind: Pod
metadata:
  name: pods-simple-pod
spec:
  serviceAccountName: {{ include "wordpress.serviceAccountName" . }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 4 }}
  containers:
    - image: busybox
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      name: pods-simple-container
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: data
          mountPath: /var/www/html
          subPath: wordpress
  volumes:
    # - name: data
    #   hostPath:
    #     path: /tmp/wordpress
    #     type: DirectoryOrCreate
    - name: data
      persistentVolumeClaim:
        claimName: {{ include "wordpress.fullname" . }}
*/}}
