apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}
type: Opaque
data:
  mysqlUsername: {{ .Values.wordpress.mysqlUsername | b64enc }}
  mysqlPassword: {{ .Values.wordpress.mysqlPassword | b64enc }}
