apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mongodb.fullname" . }}
spec:
  storageClassName: {{ include "mongodb.fullname" . }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  # claimRef:
  #   namespace: {{ .Values.namespace }}
  #   name: {{ include "mongodb.fullname" . }}
  #   # or, if using the automatic volume claim templates for stateful set
  #   name: {{ include "mongodb.fullname" . }}-{{ include "mongodb.fullname" . }}-0 . }}
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: {{ .Values.persistentVolume.diskId }}
    fsType: {{ .Values.persistentVolume.fsType }}
