apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}
type: Opaque
data:
  rootUsername: {{ .Values.mongodb.rootUsername | b64enc }}
  rootPassword: {{ .Values.mongodb.rootPassword | b64enc }}
  appUsername: {{ .Values.mongodb.appUsername | b64enc }}
  appPassword: {{ .Values.mongodb.appPassword | b64enc }}
