apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:php8.1-apache
          imagePullPolicy: Always
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql.mysql:3306
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: db-password
            - name: WORDPRESS_TABLE_PREFIX
              value: wp_
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /wp-login.php
              port: http
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /wp-login.php
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /var/www/html
              name: data
              subPath: wordpress
          resources:
            requests:
              cpu: 500m
              memory: 750Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wordpress-pvc
        ## For SMB Azure file share
        # - name: data
        #   csi:
        #     driver: file.csi.azure.com
        #     volumeAttributes:
        #       secretName: wordpress-secret
        #       shareName: {{ .Values.storageShare.name }}
        #       mountOptions: "dir_mode=0777,file_mode=0777,cache=strict,actimeo=30"
