apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 32Gi
  selector: 
    matchLabels:
      type: nfs

## For SMB Azure file share
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: wordpress-pvc
#   namespace: {{ .Values.namespace }}
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: ""
#   resources:
#     requests:
#       storage: 32Gi
#   volumeName: wordpress-pv
