apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.storageShare.nfsInternalDNSOrIP }}
    path: {{ .Values.storageShare.nfsMountPath }}

## For SMB Azure file share
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: wordpress-pv
# spec:
#   capacity:
#     storage: 32Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   csi:
#     driver: file.csi.azure.com
#     readOnly: false
#     volumeHandle: wordpress-pv
#     volumeAttributes:
#       shareName: {{ .Values.storageShare.name }}
#       storageAccount: {{ .Values.storageShare.storageAccount }}
#       resourceGroup: {{ .Values.storageShare.resourceGroup }}
#   mountOptions:
#     - dir_mode=0777
#     - file_mode=0777
#     - uid=0
#     - gid=0
#     - mfsymlinks
#     - cache=strict
#     - nosharesock
#     - nobrl
