kind: Secret
apiVersion: v1
metadata:
  name: wordpress-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  db-password: {{ .Values.dbPassword | b64enc }}
## For SMB Azure file share
#   azurestorageaccountname: {{/* .Values.storageShare.storageAccount | b64enc */}}
#   azurestorageaccountkey: {{/* .Values.storageShare.storageAccountKey | b64enc */}}
