kind: Service
apiVersion: v1
metadata:
  name: wordpress-internal-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: wordpress
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
